### ISSUE TITLE
Addon im Installer verfügbar machen

### ISSUE THREAD

**Issue by iceman-fx** [FriendsOfREDAXO/http_header#15]

**Comment by olien** [comment]
ok. dann aber als superbetaversion...

**Comment by olien** [comment]
Hm. Habs versucht. Ist alle in MyREDAXO. Finde es aber im Installer nicht.... *HELP PLEASE*

**Comment by tbaddade** [comment]
> Finde es aber im Installer nicht.... HELP PLEASE

Du hast keine Version (zip) vom AddOn hochgeladen.

**Comment by olien** [comment]
UPS. Das könnt der Grund sein ;-))
Wird nachgereicht..

-- 
Via Handy

**Comment by olien** [comment]
<img width="962" alt="image" src="https://user-images.githubusercontent.com/330516/123437146-a817a300-d5cf-11eb-8ec8-e9404e5e02ef.png">
