### ISSUE TITLE
Meldung, dass die Cookies nicht sicher sind

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/http_header#8]
![image](https://user-images.githubusercontent.com/330516/91455075-f231da00-e881-11ea-8b86-1e84363ac94a.png)

Da wird immer eine php_session_id als cookie gesendet und die Tests behaupten, dies sei ein  Sicherheitsrisiko weil das secure-flag und/oder das http-only-flag nicht gesetzt sei

**Comment by skerbis** [comment]
https://owasp.org/www-community/controls/SecureFlag
